### ISSUE TITLE
Proper Page Header

### ISSUE THREAD

**Issue by brianolson** [brianolson/ballotstudio#11]
double check reference ballot design documents. make a proper header like
```
California General Election, 2022-11-08
Some Town, Precinct 1234, page 1/3
```
Put this at the top left just inside the border box.
Probably needs to be some combination of text and template. Set up the header at the 'Election' level and let ballot styles fill in some templated parts.

**Comment by brianolson** [comment]
from EAC Effective Election Design
```
Official Ballot for General Election
Springfield County, Nebraska
Tuesday, November 07, 2006
```
[with "1/5" (page 1 of 5) right justified]

may also need to note party in the ballot header if it is a partisan primary ballot.

**Comment by brianolson** [comment]
The header text or template should probably be an extension onto the BallotStyle object or Election object.

**Comment by brianolson** [comment]
Implemented at the BallotStyle level with extension text field "PageHeader".
TODO: set "PageHeader" at "Election" level with additional template fields from BallotStyle.GpUnitIds

**Comment by ion-oset** [comment]
Ported to TrustTheVote-Project/BallotStudio#4

**Comment by brianolson** [comment]
moved https://github.com/TrustTheVote-Project/BallotStudio/issues/4
